name: ml-playground
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - cudatoolkit=11.3.1
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - matplotlib=3.5.2
  - pip:
    - music21==8.1.0
    - pyFluidSynth==1.3.1
